# Generated by Django 4.0.6 on 2022-08-07 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detourapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='detourapi.detouruser'),
        ),
    ]
